// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uztbrknwvwikkiwyhisg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6dGJya253dndpa2tpd3loaXNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTk5MDksImV4cCI6MjA3NDM5NTkwOX0.5hTcyWZNXKOpNNMO2bBGhFGByYeQiHfjiKkF2LVqlhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});